### ISSUE TITLE
[BUG] Unable to provide a client to AbstractMigration class

### ISSUE THREAD

**Issue by willsoto** [halvardssm/deno-nessie#112]
**System (please complete the following information):**

- OS: macos
- Deno version

```
deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

- Nessie version `1.2.4`

**Describe the bug** A clear and concise description of what the bug is.

I cannot provide a client to the `AbstractMigration` class as specified in the [examples](https://github.com/halvardssm/deno-nessie/blob/main/examples/migration-class-experimental.ts#L6) and docs.

**To Reproduce** Steps to reproduce the behavior:

1. Write a migration file and provide the `Client` to the `AbstractMigration` class
2. Migration doesn't compile
3. See error

**Expected behavior** A clear and concise description of what you expected to
happen.

Migration should compile when providing a `Client`

**Screenshots or error log** If applicable, add screenshots or error log to help
explain your problem.

<img width="1005" alt="Screen Shot 2021-05-07 at 2 40 31 PM" src="https://user-images.githubusercontent.com/2791730/117494682-ae2fc280-af42-11eb-84c2-64f450a2a3b0.png">
<img width="658" alt="Screen Shot 2021-05-07 at 2 41 35 PM" src="https://user-images.githubusercontent.com/2791730/117494686-aec85900-af42-11eb-9745-c3e90049003f.png">

**Additional context** Add any other context about the problem here.

I have tried `postgres@v0.4.5` (what is in the docs) and `postgres@v0.11.2` (latest) - both fail to compile.

**Comment by halvardssm** [comment]
Hi @willsoto ! I mentioned this in #111 as well, but I will mention it here as well for future reference in case anyone stumbles across the same. This is how you should use the generic type:

```ts
import {AbstractMigration, ClientPostgreSQL} from "https://deno.land/x/nessie@1.2.4/mod.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
```

By doing this, you will see the proper typehint.

Let me know if this solves it!

**Comment by willsoto** [comment]
That works! Thanks
