### ISSUE TITLE
Rollback using nessie v2 wiped my whole database 

### ISSUE THREAD

**Issue by richardanaya** [halvardssm/deno-nessie#123]
the command:

`deno run -A --unstable https://deno.land/x/nessie/cli.ts rollback`

<img width="887" alt="Screen Shot 2021-05-26 at 9 08 52 PM" src="https://user-images.githubusercontent.com/294042/119764683-b8205380-be66-11eb-970b-9db101d0237b.png">

in your v2 documentation you say it should only rollback 1 by default

<img width="894" alt="Screen Shot 2021-05-26 at 9 10 56 PM" src="https://user-images.githubusercontent.com/294042/119764781-e4d46b00-be66-11eb-858a-3d12d580a8dd.png">

**Comment by halvardssm** [comment]
Hi @richardanaya ! Good thing you caught this! I wonder why the tests didn't catch this, but it seems like they are due for an improvement! I will get a hotfix out for this today 💪🏻

**Comment by halvardssm** [comment]
Released version 2.0.0-rc3! It should be fixed now, but let me know if you are still experiencing the issue

**Comment by richardanaya** [comment]
Verified fixed, and checked the other options too :)
