### ISSUE TITLE
[IDEA] Nessie Docker image

### ISSUE THREAD

**Issue by halvardssm** [halvardssm/deno-nessie#126]
With the release of the official deno docker image https://github.com/denoland/deno_docker/pull/136 and Nessie v2, a docker image should be present to use as a part of pipelines and local development where docker is heavily used.

**Comment by richardanaya** [comment]
I could see this being really useful to folks who aren't familiar with the deno eco system and want just a simple command.

**Comment by halvardssm** [comment]
@richardanaya There is a release candidate available in the v2 brach, you can already try out the image using the instructions found in the readme 💪🏻
