### ISSUE TITLE
[IDEA]: Restrict permissions in README

### ISSUE THREAD

**Issue by ebebbington** [halvardssm/deno-nessie#137]
### The Idea

i think it would be great if the readme enforced the idea of strictor permissions, ie instead of `-A`, it'd be `--allow-write=db`

**Comment by halvardssm** [comment]
Hi @ebebbington ! I am aiming for the examples to be as beginner-friendly as possible, so I will assume that those who are seeking stricter permissions also knows how to use them. That being said, I am not opposed to adding this to the readme, so feel free to submit a PR with an _aditional_ example in the readme for the stricter permission 👍🏻

**Comment by ebebbington** [comment]
> Hi @ebebbington ! I am aiming for the examples to be as beginner-friendly as possible, so I will assume that those who are seeking stricter permissions also knows how to use them. That being said, I am not opposed to adding this to the readme, so feel free to submit a PR with an _aditional_ example in the readme for the stricter permission 👍🏻

will try get to this at some point then 👍

**Comment by ebebbington** [comment]
actually @halvardssm, whilst i understand your point, i *personally* think it can be more detrimental to use `-A`, because then it shows these users that they can just use `-A` willy nilly, whereas with the restrict permissions:

- explicitely tells the user what nessie will do
- doesn't discourage people (whilst may make it simpler for beginners, may turn off experienced developers)

And it really seems like your target audience would be other experienced developers who would end up using `nessie` for a production app and/or integrated into existing software in a company project

But i don't want it to sound like i'm being forceful or anything, i'm really just trying to look out for nessie, and if you dont agree with the above, thats ok :)
