### ISSUE TITLE
404 Not Found for std@v0.17.0/fmt/colors.ts

### ISSUE THREAD

**Issue by RomainCscn** [halvardssm/deno-nessie#15]
When trying to run `deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make example`, I have the following error:
```bash
error: Uncaught Error: Import 'https://deno.land/std@v0.17.0/fmt/colors.ts' failed: 404 Not Found
```

I'm using `deno 1.0.0-rc3`.

**Comment by halvardssm** [comment]
Hi @RomainCscn , thanks for reporting this bug! I am waiting for v 1.0 of Deno which will be released later today at some point before I go about fixing this so that we don't have to worry with regards to breaking changes. I assume I will have a fix ready by tomorrow (if not earlier) 💪

**Comment by RomainCscn** [comment]
Perfect, looking forward to testing your lib 👍

**Comment by halvardssm** [comment]
@RomainCscn It should work without problems now 👍
