### ISSUE TITLE
[IDEA]: Mariadb example 

### ISSUE THREAD

**Issue by ralyodio** [halvardssm/deno-nessie#151]
### The Idea

Can we get a Mariadb example?

**Comment by halvardssm** [comment]
Hi @ralyodio ! The MySQL example should also cover MariaDB. Is there anything for the MySQL example that does not work?

**Comment by halvardssm** [comment]
Will close as MariaDB is covered by MySQL. If there is still missing documentation, write it here and I will reopen the issue.
