### ISSUE TITLE
unable to connect to postgres

### ISSUE THREAD

**Issue by aronhoyer** [halvardssm/deno-nessie#20]
i'm running postgres through docker, exposing `5432` as the port.

i've setup the nessie config

```ts
import { nessieConfig } from "https://deno.land/x/nessie/mod.ts";
import "https://deno.land/x/denv/mod.ts";

const config: nessieConfig = {
  migrationFolder: "./migrations",
  connection: {
    user: Deno.env.get("DB_USER"),
    password: Deno.env.get("DB_PWD"),
    database: Deno.env.get("DB_NAME"),
    hostname: Deno.env.get("DB_HOST"),
    port: 5432,
  },
  dialect: "pg",
};

export default config;
```

and running `deno run --allow-net --allow-env --allow-read https://deno.land/x/nessie/cli.ts migrate -c ./nessie.config.ts` yields

```
ConnectionRefused: Connection refused (os error 61)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.connect ($deno$/net.ts:180:11)
    at async Connection.startup (https://deno.land/x/postgres@v0.4.0/connection.ts:138:17)
    at async Client.connect (https://deno.land/x/postgres@v0.4.0/client.ts:14:5)
    at async State.initClient (https://deno.land/x/nessie/cli/state.ts:99:9)
    at async run (https://deno.land/x/nessie/cli.ts:35:7)
```

from what i can tell by some cheap console.log debugging, the specified config isn't read and always defaults to

```js
{
 database: "nessie",
 hostname: "localhost",
 port: 5000,
 user: "root",
 password: "pwd"
}
```

**Comment by aronhoyer** [comment]
Seems to me like there’s an issue with how the config file is imported in the `init` method. Are you sure absolute paths are supported?

**Comment by halvardssm** [comment]
Hi @aronhoyer , thanks for reporting the bug! There seems to be an issue in the path resolving as you said, I have made a pr, and hopefully, I will have it fixed tomorrow after testing 👍

**Comment by aronhoyer** [comment]
it should also be noted that dynamically importing a file that itself imports something, seems to screw things up.

> ```ts
> import { nessieConfig } from "https://deno.land/x/nessie/mod.ts";
> import "https://deno.land/x/denv/mod.ts";
> ```

i've seen both in your cli and a quick sandbox test i just did, that `default` becomes 'undefined` as soon as something is imported to the file we're importing dynamically.

obviously this is an issue out of this packages control, but might be and idea to note in the docs until deno resolves the issue

**Comment by halvardssm** [comment]
@aronhoyer it is fixed in v0.4.1, let me know if you have any other issues 👍

**Comment by 22mahmoud** [comment]
I still get ```Connection refused ``` error.

**Comment by aronhoyer** [comment]
i'm wondering, whether you'd have to include the `file://` protocol in your dynamic import. i sandboxed a similar project just to test out similar solutions, and if i remember correctly, that was the trick i came up with.

**Comment by halvardssm** [comment]
@22mahmoud did you run it with the `--reload` flag?
@aronhoyer `file://` was added in #21 since the dynamic import refused to fetch the local files without. Do you know if this is a permanent feature, or if it is a temporary bug?

Are both of you still having the same issue? Can you paste the error log here or in a gist?

**Comment by 22mahmoud** [comment]
@halvardssm It works for me with ```--reload``` flag, thank you.

**Comment by aronhoyer** [comment]
> Do you know if this is a permanent feature, or if it is a temporary bug?

i believe it to be permanent, @halvardssm, since deno's module resolution is url based. and, since this use case kinda requires the import to come from outside the project directory, i deduce that's the reason that `file://` is required. i might just be talking out of my butt, so i dunno tbh 🤷‍♂️

> Are both of you still having the same issue?

i haven't tried it yet, but i'll let you know if i encounter the bug again once i get back into it 😄
