### ISSUE TITLE
Bundling nessie and running it doesn't work

### ISSUE THREAD

**Issue by leabstrait** [halvardssm/deno-nessie#22]
I want to run Nessie with a shorter command than to type out the whole URL. So I opted for this 'bundling' solution as pointed out in the discord server of deno. However, I have a problem.

```➜ deno bundle https://deno.land/x/nessie/cli.ts deps/nessie_cli.ts``` 
```Bundling https://deno.land/x/nessie/cli.ts
Emitting bundle to "deps/nessie_cli.ts"
1450193 bytes emitted.
```

[Okay, bundling is done]

```➜ deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make initialize_db```
```
Created migration 1589728502895-initialize_db.ts at /home/***/***/migrations
```

[Migration gets created when running from a remote URL]

```➜ deno run --allow-net --allow-read --allow-write deps/nessie.ts make initialize_db ```

[However, this does nothing]

**Comment by halvardssm** [comment]
Hi @leabstrait ! Thanks for letting me know of this! I haven't tried to bundle it until now, but I can see it being a useful feature. I will add it to the roadmap of v1. I will probably not deal with it until the rest of the functionalities are implemented, but it will be on the list 💪

**Comment by halvardssm** [comment]
Hi @leabstrait ! I think bundling finally works with Deno 1.0.5 and with Nessie 0.5.2 🎉 Can you confirm this? 
`deno bundle https://deno.land/x/nessie@v0.5.2/cli.ts nessie_cli.js`
`deno run --allow-net --allow-read --allow-write nessie_cli.js init`

**Comment by leabstrait** [comment]
Hi @halvardssm,

Yes it works @v0.5.2 

Also, the bundle is a .js file, I see. I was trying to bundle it to .ts extension at first, but while running it, there were errors about typing. I changed it to .js and it worked promptly. Not a problem for me, just an observation.

I came to this problem when thinking of a solution like python virtualenvs which let you use specific versions of packages for one project. Since deno install did a global install, I had wanted something project-local. 

Your fix of bundling solved this issue. But as I spend more time with deno, I don't know if python's virtualenv solution applies here, especially when you can specify versions in the URL itself and use a deps.ts to manage project dependencies.

Anyways great, thanks. You can close this issue as you see fit.

**Comment by halvardssm** [comment]
Great! `deno bundle` bundles the code into ESM JS so that it can run without the tsc overlay, I dont think bundling to TS will be supported anytime soon 🤔 Technically you can achieve what you want, but you will have to bundle each and every external module manually, and also get the types separately. I would probably use `deps.ts` for now and maybe move over to import maps when this is stable 💪
