### ISSUE TITLE
Order of migrations is in descending order of timestamps

### ISSUE THREAD

**Issue by leabstrait** [halvardssm/deno-nessie#23]
I am getting migrations applied in descending order. 

![image](https://user-images.githubusercontent.com/21138552/82415898-ec657500-9a98-11ea-99c3-b2d865788ab1.png)

Also from the debug log:
```
Files after filter and sort: 
[
 {
   name: "1589953809972-create_extension_uuid_ossp.ts",
   isFile: true,
   isDirectory: false,
   isSymlink: false
  },
 {
   name: "1589951602231-create_schema_auth.ts",
   isFile: true,
   isDirectory: false,
   isSymlink: false
  }
]
```

**Comment by halvardssm** [comment]
Thanks for reporting this bug! Also great that you created a PR for it, cheers! 👍
