### ISSUE TITLE
Rollback not consistent with the order of migration script it uses

### ISSUE THREAD

**Issue by leabstrait** [halvardssm/deno-nessie#25]
```
➜  server git:(master) ✗ nessie migrate 
Migrated 1590069251844-create_schema_auth.ts
Migrated 1590069327251-create_extension_uuid_ossp.ts
Migrated 1590070232932-create_table_auth_users.ts
Migration complete

➜  server git:(master) ✗ nessie rollback
Rolled back 1590070232932-create_table_auth_users.ts

➜  server git:(master) ✗ nessie rollback
Rolled back 1590069327251-create_extension_uuid_ossp.ts

➜  server git:(master) ✗ nessie rollback
Rolled back 1590069251844-create_schema_auth.ts

➜  server git:(master) ✗ nessie rollback
Nothing to rollback

=============================================

➜  server git:(master) ✗ nessie migrate 
Migrated 1590069251844-create_schema_auth.ts
Migrated 1590069327251-create_extension_uuid_ossp.ts
Migrated 1590070232932-create_table_auth_users.ts
Migration complete

➜  server git:(master) ✗ nessie rollback
Rolled back 1590070232932-create_table_auth_users.ts

➜  server git:(master) ✗ nessie rollback
PostgresError: cannot drop schema auth because other objects depend on it
    at parseError (https://deno.land/x/postgres@v0.4.0/error.ts:105:10)
    at Connection._processError (https://deno.land/x/postgres@v0.4.0/connection.ts:421:19)
    at Connection._simpleQuery (https://deno.land/x/postgres@v0.4.0/connection.ts:292:20)
    at async Connection.query (https://deno.land/x/postgres@v0.4.0/connection.ts:526:14)
    at async Client.query (https://deno.land/x/postgres@v0.4.0/client.ts:24:12)
    at async https://deno.land/x/nessie/cli/pgsql.ts:60:28
    at async queryHandler (https://deno.land/x/nessie/cli/utils.ts:135:20)
    at async https://deno.land/x/nessie/cli/pgsql.ts:57:9
    at async traverseAndRollbackFiles (https://deno.land/x/nessie/cli/utils.ts:110:5)
    at async PGSQL.rollback (https://deno.land/x/nessie/cli/pgsql.ts:53:5)
```

Above is a sample run, reproduced a number of times. The migrate and rollback sequence seems to work at first but upon a further run, nessie fails at rollback. I think the reason is due to the migrations being carried out in a short time frame, such that when doing a rollback it can't figure out which one was the last migration. 
Here's a part of the debug log:
```
Rollback query: 
DROP SCHEMA auth;
Queries: 
[
  "DROP SCHEMA auth",
  "DELETE FROM nessie_migrations WHERE file_name = '1590069251844-create_schema_auth.ts'"
]
Query: 
DROP SCHEMA auth
PostgresError: cannot drop schema auth because other objects depend on it
```

It skipped the latest migration record in the nessie_migrations table in favor of an older one.

The code in `utils.ts` has the following line:
```
export const QUERY_GET_LATEST =
  `select ${COL_FILE_NAME} from ${TABLE_MIGRATIONS} order by ${COL_CREATED_AT} desc limit 1`;
```
I believe when carrying out migrations in bulk the COL_CREATED_AT doesn't provide a fine enough distinction while adjacent migration scripts run.

I propose using:
`select max(${COL_FILE_NAME}) from ${TABLE_MIGRATIONS};`
OR
  `select ${COL_FILE_NAME} from ${TABLE_MIGRATIONS} order by ${COL_FILE_NAME} desc limit 1`;

The first one however causes a bug in another issue I'll mention after solving this one. The second one will work but might have to keep this in mind (just discovered): [Year 2038 Problem](https://en.wikipedia.org/wiki/Year_2038_problem)

Thanks.

**Comment by halvardssm** [comment]
Hi @leabstrait ! Thanks for filing this bug! 

Regarding the first proposal, is it the bug in #26 ? I don't think there are any edge cases for using 
`select max(${COL_FILE_NAME}) from ${TABLE_MIGRATIONS};`
except for if we were to allow multiple migration files to be created at the same time (but will that ever be the case 🤔 ). Looking at the execution time, it is also faster to use this query.

I think the best course of action is to use `max`. Would you like to make a pr for this?

**Comment by leabstrait** [comment]
I used `max` but it fails for the check in `filterAndSortFiles`:

`if (queryResult === undefined) return true;`

because queryResult would then be null, and not `undefined`. 


Okay I'll look into it and send a PR, if possible using the first proposed query.

**Comment by halvardssm** [comment]
@leabstrait Sounds good! If you make it work, can you also add a test case to cover this issue?
