### ISSUE TITLE
Bulk migration works, migration of the last few files doesn't

### ISSUE THREAD

**Issue by leabstrait** [halvardssm/deno-nessie#26]
```
➜  server git:(master) ✗ deno-nessie migrate                     
Migrated 1590069251844-create_schema_auth.ts
Migrated 1590069327251-create_extension_uuid_ossp.ts
Migrated 1590070232932-create_table_auth_users.ts
Migration complete

➜  server git:(master) ✗ deno-nessie rollback
Rolled back 1590070232932-create_table_auth_users.ts
➜  server git:(master) ✗ deno-nessie migrate 
Nothing to migrate
```

In the above series of commands I run one rollback after a bulk migration. That rollback reversed one migration but trying to migrate again from this point I get `Nothing to migrate`. I believe the remaining un-migrated script must run but that is not the case.

I think issue #25 must be fixed before this because that gives the correct 'latest migration'. I have a solution that changes `filterAndSortFiles` function in `utils.ts`. I'll add it after issue #25 is resolved.

**Comment by halvardssm** [comment]
@leabstrait thanks for filing this bug! Let's get back to this one after #25 is fixed 👍

**Comment by halvardssm** [comment]
@leabstrait Is this one solved for you after the last merge?

**Comment by leabstrait** [comment]
Yes it's solved. it can be closed. The tests covered both issues #25 and #26
