### ISSUE TITLE
PostgresError: syntax error at or near "\"

### ISSUE THREAD

**Issue by bander-saeed94** [halvardssm/deno-nessie#39]
When Running migrate with a create table that has timestampsTz().

The error:
Error:CREATE OR REPLACE FUNCTION trigger_set_timestamp() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now()\; RETURN NEW\; END\; $$ language 'plpgsql';CREATE TABLE tbl_user (id uuid PRIMARY KEY, username varchar (25) not null UNIQUE, email varchar (35) default null UNIQUE, phone_number numeric (12) default null UNIQUE, fullname varchar (40), password varchar (100), email_confirmed boolean default false, phone_number_confirmed boolean default false, created_at timestamptz (0) default current_timestamp, updated_at timestamptz (0) default current_timestamp); DROP TRIGGER IF EXISTS set_timestamp on tbl_user; CREATE TRIGGER set_timestamp BEFORE UPDATE ON tbl_user FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();INSERT INTO nessie_migrations (file_name) VALUES ('1590656398438-create-user-table.ts');
PostgresError: syntax error at or near "\\"
    at ClientPostgreSQL.query (https://deno.land/x/nessie/clients/ClientPostgreSQL.ts:50:13)
    at async ClientPostgreSQL.migrate (https://deno.land/x/nessie/clients/AbstractClient.ts:83:9)
    at async ClientPostgreSQL.migrate (https://deno.land/x/nessie/clients/ClientPostgreSQL.ts:62:5)
    at async run (https://deno.land/x/nessie/cli.ts:62:11)

**Comment by halvardssm** [comment]
Hi! Unfortunately, during the transition from the previous to the new structure, `updatedAt` and `updatedAtTz` ended up with a bug. It's currently on the top of my list 👍

**Comment by Leonardo-Rocha** [comment]
I'm facing the same problem here. Waiting for a fix.
The other things are working pretty well, thanks @halvardssm !

**Comment by halvardssm** [comment]
@bander-saeed94 @Leonardo-Rocha version 0.5.1 is now released which fixes this issue 👍

**Comment by Leonardo-Rocha** [comment]
Working just fine now. Thanks!
