### ISSUE TITLE
Default string value

### ISSUE THREAD

**Issue by bander-saeed94** [halvardssm/deno-nessie#41]
having a varchar with default value 
table.string("name", 100).default("update wallet name");

toSql:
CREATE TABLE tbl_wallet (name varchar (100) default update wallet name)

expected:
CREATE TABLE tbl_wallet (name varchar (100) default 'update wallet name')

**Comment by halvardssm** [comment]
Thanks for reporting this bug! Will put it on the list

**Comment by bander-saeed94** [comment]
I am planing to do it this way in Clomun.ts
//
```    
if (this.defaultValue) {
      if (
        this.columnType == "TEXT" ||
        this.columnType == "CHAR" ||
        this.columnType == "MEDIUMTEXT" ||
        this.columnType == "TINYTEXT" ||
        this.columnType == "VARCHAR" ||
        this.columnType == "character" ||
        this.columnType == "char" ||
        this.columnType == "character varying" ||
        this.columnType == "varchar" ||
        this.columnType == "text" 
      ) {
        string += ` default '${this.defaultValue}'`;
      } else {
        string += ` default ${this.defaultValue}`;
      }
    }
```

**Comment by halvardssm** [comment]
@bander-saeed94 Are we sure that only these types should be wrapped in `'`? Are there any documentation regarding this? If so, I'm all for it. Want to give it a go?

**Comment by bander-saeed94** [comment]
No, I am not sure. I will google it and share my findings. 
We also need to consider null. Even though the column type is a string it shall not be in a single quote. we might introduce a function to set a default value to null.

**Comment by bander-saeed94** [comment]
So, after you told me about Dex. I checked it and found it is based on knex internally.
I checked the source code:
https://github.com/knex/knex/blob/da54cf1ecf0acef4b3d3d51cd2656e4faf10d3e9/lib/schema/columncompiler.js

I find this piece of code helpful
```
ColumnCompiler.prototype.defaultTo = function (value) {
  if (value === void 0) {
    return '';
  } else if (value === null) {
    value = 'null';
  } else if (value instanceof Raw) {
    value = value.toQuery();
  } else if (this.type === 'bool') {
    if (value === 'false') value = 0;
    value = `'${value ? 1 : 0}'`;
  } else if (
    (this.type === 'json' || this.type === 'jsonb') &&
    isObject(value)
  ) {
    value = `'${JSON.stringify(value)}'`;
  } else {
    value = `'${value}'`;
  }
  return `default ${value}`;
};
```

**Comment by halvardssm** [comment]
That seems like a useful implementation, if you use it, please leave a javadoc stating where it is from (like a link to the file+line or something) 👍 The logic for default is found in `query-builder/Column.ts`
