### ISSUE TITLE
[Discussion/Poll] Bring back exposed schema in the migration files

### ISSUE THREAD

**Issue by halvardssm** [halvardssm/deno-nessie#46]
In the initial versions of Nessie, the query-builder was exposed in the migration methods `up` and `down`. In v0.5 this was removed to reduce the files you had to download if you only wanted to use the migration tool and not the built-in query builder, or if you prefer a third-party tool like Dex (port of knex).

From what I can see, we have these options (I'm personally leaning towards the first one)

🎉 Dynamically import the query builder and expose the schema in the migration files if a property in the config file is true i.e. `exposeSchema: true`. 

🚀 No exposure of the query builder in the migration files. If you want to use the query builder, you can import it manually.

❤️ Always expose the query builder even if it causes extra files to be downloaded. 

Feel free to comment if you have any thoughts or ideas, or if you just want to vote on the idea you like the most, use the emojis 😄

**Comment by halvardssm** [comment]
@awildeep @leabstrait @bander-saeed94 Do you have any thoughts about this? (calling you guys since you have the history of being the most active here) 😄

**Comment by awildeep** [comment]
To be fair, I have not been using the query builder much at all as a lot of my current code requires writing postgresql specific functions, triggers and partitions that are not supported and probably are not widely used enough to even consider.  I lean toward whatever method I can use to disable loading the query builder at all that fits your time and schedule.

**Comment by bander-saeed94** [comment]
Hi @halvardssm I would go with decoupling as the modular way you have done. 
It would nice to have ```exposeSchema: true``` but I don't think should be a priority.
