### ISSUE TITLE
[BUG] the migration file name

### ISSUE THREAD

**Issue by kitchanismo** [halvardssm/deno-nessie#49]
**Describe the bug**
The migration file name after timestamp became 'true' after make command.
1591215665344-true.ts

**To Reproduce**
 deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make create_users

**Expected behavior**
1591215665344-create_users.ts

**System (please complete the following information):**
 - OS: Windows 10
 - Deno version : 1.0.3
 - Nessie version: 0.5.2

**Comment by halvardssm** [comment]
@kitchanismo Should be fixed in v0.5.3 👍
