### ISSUE TITLE
[IDEA] Strict fields within create function in Model

### ISSUE THREAD

**Issue by kitchanismo** [halvardssm/deno-nessie#50]
**Is your feature request related to a problem? Please describe.**
I want to implement repository pattern. It makes the code robust. 

**Describe the solution you'd like**
maybe you can get those fields from model itself.

**Comment by halvardssm** [comment]
Hi @kitchanismo ! Thanks for the idea! Could you explain how you would like to implement the repository pattern and also add some examples? Also, do you mean the query builder, clients, or the cli?

**Comment by halvardssm** [comment]
As there haven't been any updates on this issue, I will close it for now
