### ISSUE TITLE
Update Readme, Object is possibly 'undefined'

### ISSUE THREAD

**Issue by bander-saeed94** [halvardssm/deno-nessie#56]
**Describe the bug**
Object is possibly 'undefined'

**To Reproduce**
Having 
```
export const up: Migration<Schema> = ({ queryBuilder }) => {
  queryBuilder.create("users", (table) => {
    table.id();
    table.string("name", 100).nullable();
    table.boolean("is_true").default("false");
    table.custom("custom_column int default 1");
    table.timestamps();
  });

  queryBuilder.queryString(
    "INSERT INTO users VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);",
  )
  
  return queryBuilder.query
};
```

I overcome it by adding exclamation mark:
```
export const up: Migration<Schema> = ({ queryBuilder }) => {
  return queryBuilder!.create("tbl_user", (table) => {
    table.uuid("id").primary();
    table.string("username", 25).notNullable().unique();
    table.string("email", 35).nullable().default(null).unique();
    table.numeric("phone_number", 12, 0).nullable().default(null).unique(); //9665xxxxxxxx
    table.string("fullname", 40);
    table.string("password", 100);
    table.boolean("email_confirmed").default(false);
    table.boolean("phone_number_confirmed").default(false);
    table.uuid("email_hash");
    table.string("otp_secret", 60);
    table.timestampsTz();
  });
};
```

**Comment by halvardssm** [comment]
Which Nessie version are you on?

**Comment by bander-saeed94** [comment]
Latest. I just run `--reload `
This is because queryBuilder type is: Schema | undefined

**Comment by bander-saeed94** [comment]
![image](https://user-images.githubusercontent.com/29840356/83919849-2cf50c00-a784-11ea-8427-19820dbe21aa.png)

**Comment by halvardssm** [comment]
It is fixed in rc2 👍

**Comment by bander-saeed94** [comment]
Hello @halvardssm I think the issue still exists

**Comment by halvardssm** [comment]
What issue are you facing? It looks fine for me after refreshing the cache (adding the `-r` flag) 
<img width="558" alt="Screenshot 2020-06-08 at 22 25 05" src="https://user-images.githubusercontent.com/33620089/84077039-484f5980-a9c6-11ea-8ad0-74e61b863125.png">
<img width="558" alt="Screenshot 2020-06-08 at 22 25 22" src="https://user-images.githubusercontent.com/33620089/84077043-4a191d00-a9c6-11ea-9dc6-372ee53c5610.png">

**Comment by bander-saeed94** [comment]
Yah, it is working. Thanks
