### ISSUE TITLE
[BUG] [ERROR]: Property 'queryBuilder' is missing in type

### ISSUE THREAD

**Issue by seljabali** [halvardssm/deno-nessie#59]
**System (please complete the following information):**
 - OS: Mac 10.13.6 
 - Deno version 1.0.0
 - Nessie version v1.0.0-rc2

**Describe the bug**
I run the following to init:
```
➜  deno_sample deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts init
```
& get [ERROR]: Property 'queryBuilder' is missing in type error.

**To Reproduce**
1. Run `deno_sample deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts init`
2. See error

**Expected behavior**
`nessie.config.ts` is created.

**Screenshots or error log**
```
error: TS2741 [ERROR]: Property 'queryBuilder' is missing in type '{ dialect: DBDialects; connection: QueryHandler; }' but required in type 'Info<undefined>'.
    const exposedObject: Info = {
          ~~~~~~~~~~~~~
    at https://deno.land/x/nessie/clients/AbstractClient.ts:194:11

    'queryBuilder' is declared here.
      queryBuilder: T;
      ~~~~~~~~~~~~
        at https://deno.land/x/nessie/types.ts:10:3
```

**Additional context**
NA

**Comment by halvardssm** [comment]
Hi @seljabali ! Thanks for repporting this bug! It will be fixed when #58 lands 👍

**Comment by inmanturbo** [comment]
I can confirm the same issue. Excitedly waiting the fix! Look like it will be a great package!

**Comment by halvardssm** [comment]
@seljabali @inmanturbo I merged the PR now, it should work in rc3 when I release it in a minute 👍

**Comment by inmanturbo** [comment]
This error still persists.

```
deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make create_users
Compile https://deno.land/x/nessie/cli.ts
error: TS2741 [ERROR]: Property 'queryBuilder' is missing in type '{ dialect: DBDialects; connection: QueryHandler; }' but required in type 'Info<undefined>'.
    const exposedObject: Info = {
          ~~~~~~~~~~~~~
    at https://deno.land/x/nessie/clients/AbstractClient.ts:194:11

    'queryBuilder' is declared here.
      queryBuilder: T;
      ~~~~~~~~~~~~
        at https://deno.land/x/nessie/types.ts:10:3

```
```
~ $ deno --version
deno 1.0.5
v8 8.4.300
typescript 3.9.2
```

**Comment by halvardssm** [comment]
@inmanturbo have you tried to run it with `—reload`?

**Comment by inmanturbo** [comment]
> @inmanturbo have you tried to run it with `—reload`?

Nope. Thanks that fixed it. Sorry Deno is still new still learning it forgot about the cache. Thanks again!

**Comment by halvardssm** [comment]
No problem!
