### ISSUE TITLE
[QUESTION] How to specify client for migration

### ISSUE THREAD

**Issue by gabrielgrover** [halvardssm/deno-nessie#61]
So I am trying to follow the read me and create a migration.  I have ran both 

```deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts init```
```deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make create_users```

What is strange is that the make create_users creates a sqllite.db file.  I would like to use postgres.  Is there some setting that I am missing?  

Here is my nessie.config

```
import { ClientPostgreSQL } from "https://deno.land/x/nessie/mod.ts";
import { ClientMySQL } from "https://deno.land/x/nessie/mod.ts";
import { ClientSQLite } from "https://deno.land/x/nessie/mod.ts";

/** These are the default config options. */
const clientOptions = {
  migrationFolder: "./db/migrations",
  seedFolder: "./db/seeds",
};

/** Select one of the supported clients */
const clientPg = new ClientPostgreSQL(clientOptions, {
  database: "deno-demo",
  hostname: "localhost",
  port: 5432,
  user: "postgres",
  password: "postgres",
});
const clientMySql = new ClientMySQL(clientOptions, {
  hostname: "localhost",
  port: 3306,
  username: "root",
  // password: "pwd", // uncomment this line for <8
  db: "nessie",
});
const clientSqLite = new ClientSQLite(clientOptions, "./sqlite.db");

/** This is the final config object */
const config = {
  client: clientPg,
  // Defaults to false, if you want the query builder exposed in migration files, set this to true.
  exposeQueryBuilder: true,
};

export default config;
```

**Comment by halvardssm** [comment]
Hi @gabrielgrover ! The nessie config generated by the init command will contain the settings for pg, mysql and sqlite. By default when `ClientSQLite` is created (`const clientSqLite = new ClientSQLite(clientOptions, "./sqlite.db");`), it will contain the path to the sqlite, and create a file accordingly. To solve this, you can simply remove the mysql and sqlite config. By default, it uses postgres so the only changes you have to do is to set the connection options. Let me know if you have any other questions 👍

**Comment by gabrielgrover** [comment]
Thanks @halvardssm that worked!  Also thanks for building this, cannot wait to explore it more!

**Comment by deadmanwalking74** [comment]
It appears nessie.config.ts is ignored when I try to run a migration. it says `this.client` is undefined.
