### ISSUE TITLE
[BUG] Error after migration makes it so I cannot rollback

### ISSUE THREAD

**Issue by gabrielgrover** [halvardssm/deno-nessie#62]
**System (please complete the following information):**
 - OS: OSX 10.14.6
 - Deno version 1.0.5

**Describe the bug**
After running the sample migration file in the README I get an error (pasted below).  The migration seems to have worked, but there wasn't an entry made in the nessie_migrations table.  Therefore when I try to rollback I get a message saying "nothing to rollback"
**To Reproduce**
create database
create migration file with the following code
```
import { Migration } from "https://deno.land/x/nessie/mod.ts";
import { Schema } from "https://deno.land/x/nessie/qb.ts";

export const up: Migration<Schema> = ({ queryBuilder }) => {
  queryBuilder.create("users", (table) => {
    table.id();
    table.string("name", 100).nullable();
    table.boolean("is_true").default("false");
    table.custom("custom_column int default 1");
    table.timestamps();
  });

  queryBuilder.queryString(
    "INSERT INTO users VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);",
  )
  
  return queryBuilder.query
};

export const down: Migration<Schema> = ({ queryBuilder }) => {
  return queryBuilder.drop("users");
};
```
run the migration 

```deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make create_users```

**Expected behavior**
The migration works without an error.  If there is an error be able to roll back the migration with 

```deno run --allow-net --allow-read https://deno.land/x/nessie/cli.ts migrate```

**Screenshots or error log**
```
Database setup complete
TODO: handle notice
Error: Error:CREATE OR REPLACE FUNCTION trigger_set_timestamp() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ language 'plpgsql';,CREATE TABLE users (id bigserial PRIMARY KEY, name varchar (100), is_true boolean DEFAULT 'false', created_at timestamp (0) DEFAULT current_timestamp, updated_at timestamp (0) DEFAULT current_timestamp, custom_column int default 1);,DROP TRIGGER IF EXISTS set_timestamp on users;,CREATE TRIGGER set_timestamp BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();,INSERT INTO users VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);,INSERT INTO nessie_migrations (file_name) VALUES ('1591974934942-create_users.ts');
PostgresError: column "created_at" is of type timestamp without time zone but expression is of type integer
    at ClientPostgreSQL.query (https://deno.land/x/nessie/clients/ClientPostgreSQL.ts:57:13)
    at async ClientPostgreSQL._migrationHandler (https://deno.land/x/nessie/clients/AbstractClient.ts:222:5)
    at async ClientPostgreSQL.migrate (https://deno.land/x/nessie/clients/AbstractClient.ts:97:9)
    at async ClientPostgreSQL.migrate (https://deno.land/x/nessie/clients/ClientPostgreSQL.ts:69:5)
    at async run (https://deno.land/x/nessie/cli.ts:74:11)
```

**Comment by halvardssm** [comment]
Hi @gabrielgrover ! Thanks for reporting this bug! The issue you are facing is because the query builder does not handle the ordering of the columns. 

To get around this, you can change your query string to 
`INSERT INTO users (id, name, is_true, custom_column, created_at, updated_at) VALUES (DEFAULT, 'Deno', true, 2, DEFAULT, DEFAULT);`
or the shorthand: 
`INSERT INTO users (name, is_true, custom_column) VALUES ('Deno', true, 2);`
or use a third-party module like [Dex](https://deno.land/x/dex) to generate the queries ([see example](https://github.com/halvardssm/deno-nessie/blob/master/examples/migration-third-party.ts)).

I will add it to the roadmap of future improvements of the query builder 👍

**Comment by halvardssm** [comment]
Will close this as the query builder is moved to https://github.com/halvardssm/deno-query-builder
