### ISSUE TITLE
[BUG] Bump deno to v1.2 and std to v0.61

### ISSUE THREAD

**Issue by njpearman** [halvardssm/deno-nessie#67]
**System (please complete the following information):**
 - OS: macos
 - Deno v1.2.0
 - Nessie 0.10.0

**Describe the bug**

Deno v1.2 has introduced a breaking change around the `URL` constructor, strictly requiring a type of `string`. This means any modules referencing `std` need to be bumped to v0.61 to work with Deno v1.2. See [https://github.com/denoland/deno/issues/5365#issuecomment-658051958](https://github.com/denoland/deno/issues/5365#issuecomment-658051958) for more details.

I've started on an upgrade to `nessie` here: [https://github.com/njpearman/deno-nessie/tree/deno-1.2](https://github.com/njpearman/deno-nessie/tree/deno-1.2) but there are dependencies that need version bumps first, so I can't open a PR until they have published upgrades. I'm creating this issue to keep a track of things. Hope that's useful :)

- [x] `denomander` upgrade, PR here: [https://github.com/siokas/denomander/pull/23](https://github.com/siokas/denomander/pull/23)
- [x] `deno-postgres` upgrade, PR here: [https://github.com/deno-postgres/deno-postgres/pull/152](https://github.com/deno-postgres/deno-postgres/pull/152)

Probably upgrades needed for MySQL and SQLite too?

**Comment by halvardssm** [comment]
Hi @njpearman ! Good thing you noticed this! You can submit the PR when you are ready, and I will review it as soon as possible to get it available with a new tag! From what I can see, Denomander and Postgres have had the update merged, but MySQL and SQLite are not yet up to date. If you submit the PR with an update to the CI (just change the Deno version to 1.2), we can see if the pipeline succeeds or not 👍

**Comment by njpearman** [comment]
Okay. It's annoying that neither `denomander` nor `deno-postgres` have tagged a version for the fixes yet so I guess it should wait until they do. I'll keep an eye out for when they do.

**Comment by halvardssm** [comment]
@njpearman Denomander now has version 0.6.3 👍

**Comment by halvardssm** [comment]
Do you want me to assign this issue to you?

**Comment by Yamboy1** [comment]
Also, as an alternative to tagged releases, it's possible to use commit hashes instead of tags, if you want a quick and dirty way to lock down the version.

**Comment by njpearman** [comment]
@halvardssm `deno-postgres` still doesn't have a release with the v1.2 upgrade but I'll use the commit hash hack as suggested by @Yamboy1 . `sqlite` is still not on Deno v1.2, which seems fine to me as I can't see any `stdlib` refs but I might be wrong.

**Comment by halvardssm** [comment]
Perfect! I actually forgot about the hash hack, but good thing @Yamboy1 thought of it! I looked over your PR, and I think we can deem it good to merge as long as the tests pass 👍

**Comment by Yamboy1** [comment]
Actually, with the new [deno_registry2](https://github.com/denoland/deno_registry2), the hash idea doesn't work anymore, you can only use tagged releases now, so i think you'll need to use github raw or something else to do that, not entirely sure tho

**Comment by Yamboy1** [comment]
ah, that's what you are doing, :+1:
