### ISSUE TITLE
[IDEA] Add an API that allows indexes to be created in standalone migrations

### ISSUE THREAD

**Issue by njpearman** [halvardssm/deno-nessie#68]
Hi,

I'm trying out `nessie` at the moment for managing a greenfield, small PostgreSQL database in a really small Deno project. I'm new to Deno and server-side JS but very used to building web apps with Ruby on Rails.

I just created a migration to add an index but had to use raw SQL to do it. This is fine with me for what I'm doing now, but do you have plans to extend out the `Schema` / `Table` classes to have an API for a migration that just adds one or more indexes to existing tables?

For reference, this is the format of migration that I'm using:

```javascript
import { Migration } from "https://deno.land/x/deno-nessie@v1.0.2/mod.ts";

export const up: Migration = () => {
  return "CREATE INDEX idx_logs_info ON logs(info);";
};

export const down: Migration = () => {
  return "DROP INDEX idx_logs_info;";
};
```

**Comment by halvardssm** [comment]
Hi @njpearman ! Good thing you brought it up! I have actually not thought about this after I discovered other query builders. After the migration and seed functionalities were completed, I found a couple of other modules focusing on being a query builder (e.g. http://deno.land/x/dex) so I decided to focus Nessie on the migration and seed functionalities and let other modules improve their query builders. Then again, Nessie currently includes a barebone SQL builder, so if PR's are submitted, I am happy to merge them :)

**Comment by njpearman** [comment]
Hey.

I see. I was a little confused which came first in your project, `QueryBuilder` or `Dex` :D

I'm keen to contribute. Between submitting this PR and your response, I've actually gone off and put together my own barebones approach to migrations, but the structure of the Migration class and files is quite different to how you've tackled it. I'm happy to share if you're interested in seeing the differences. As I mentioned, I come from Rails and think in terms of the DSL / API that Rails provides in its migrations, which is different to how things currently go in `nessie`.

The thing that I got stuck with in `nessie` is that a Migration directly returns the SQL query as a string, which presented some problems around creating indexes in isolation, and also seeding data with a parameterised query.

It struck me that the important part to me is that there should be an abstraction between the Migration class and the query builder, so that when you write a migration, it isn't done directly with a query builder that returns a SQL query as a string. I think this would help separate the database and the queries from the migrations.

This would make doing things like migrations that modify tables or other parts of the schema, like adding an index, a bit more natural. I'm not sure it'll make much sense out of context, but this is how a migration in my hacky migrator attempt looks:

```typescript
import { Migration } from "../../migrations.ts";

export const migration = new Migration(
  "202007152235",
  async (schema) => {
    const tableName = "logs";
    const columnName = "info";

    schema.createIndex(tableName, columnName); // creates an index with a name based on convention
  },
  async (schema) => {
    const tableName = "logs";
    const columnName = "info";

    schema.dropIndex(tableName, columnName); // drops an index based on the naming convention
  },
);
```

This means there would be other methods like `createTable`/`dropTable`, `addColumn`/`removeColumn`, etc. on my `Schema` class. I like this sort of clarity in migrations, and it can still be flexible to run raw SQL via a query builder if necessary.

Let me know what you think. This is obviously far wider scope than just something to add a query to create an index! Please don't take this as pushing my ideas on your project, I'm just keen to help and have been thinking about this for a couple of days :)

**Comment by halvardssm** [comment]
Well, the creation of Nessie and Dex started around the same time, and when I discovered Dex, I had already created something barebone of a QB, so I decided to just finish up a basic one in case someone found it useful.

The thing with migrations is that they should ideally be isolated instances, meaning that I should be able to take a migration file from anywhere (made with Nessie ofc) and it should simply work by changing the timestamp in the filename and without changing any imports or code. The idea behind Nessie is that it does one thing, and that one thing relatively well. This is why I went away from a migration class in favour of returning an SQL string or an array of SQL strings if need more than one query to be run. You can look at some of the earlier versions (pre v5) to see how it initially was implemented if you need inspiration, its quite similar to your approach 😄 

All this being said, it is fairly easy to add something like this to the qb. I was actually thinking about adding an altering interface to the QB, but I never got the time 😅 

I would be very interested in seeing your approach though, please share as it might give me some ideas as well!

**Comment by njpearman** [comment]
I'll try to put something together to show you next week (been a bit busy with other things this week!)

I completely agree with what you're saying about both migrations being isolated, and understand your goal to allow users to  switch in different ways of interacting with schemas.

The problem I found with making a concrete migration return a `string` or `string[]` is that it binds the way migrations are written to the assumption that the migration can be done with a string. This is not possible, for example, with a parameterised query or prepared statement. Admittedly, this is somewhat edge case but it blocked me at my first attempt to use `nessie` for seeding data with my own choice of writing the database interaction within the migration. To put it another way, I personally found it too restrictive to be forced to return SQL statements, as it prevented me from using a particular form of database interaction. Admittedly, I can't think of other scenarios at the moment, particularly around manipulating schema rather than data.

This is a question of abstractions, though, and if your goal is to ensure migrations explicitly provide SQL statements as an output, then our needs are different. It seems like that is probably the case, and means I need a different solution in order to use parameterised queries / prepared statements. 

However, if explicitly returning SQL statements isn't a goal, then I'm sure there will be a way to adjust the client parts so that they infer the execution of the migration, rather than explicitly running `queryHandler.query( ... )` on a returned `string` or `string[]`. Something like that would decouple the migration files from the operation to execute the migration, and provide a path for me to use things like parameterised queries in seed files (for example) The question is how complex it would be 😄 

I hope that makes sense!

**Comment by halvardssm** [comment]
I am open to change if the reason is sound enough, and it makes sense. I only have the requirement that it should be as minimalistic as possible, and each migration file should work independently of the nessie/deno version. I'm looking forward to seeing your proposal!

**Comment by njpearman** [comment]
Cool :)

I'll be honest, I have too many other things building up to look at this, which is a shame. If I get back around to it, I'll let you know. In the meantime, I'll use `nessie` as is and make a note of anything interesting I think of.

**Comment by halvardssm** [comment]
No worries! We can keep this issue open and keep it as a discussion thread for the design of the migrations 😄

**Comment by halvardssm** [comment]
Will close this as the query builder has been moved to https://github.com/halvardssm/deno-query-builder
