### ISSUE TITLE
[BUG] Argument of type 'string | URL' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by ThisIsMohsen** [halvardssm/deno-nessie#69]
- OS: Win 64
 - Deno version [1.2.0]
 - Nessie version [latest]

hi,
i can init configuration in first step with this command:
`deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts init`

this is output:

> error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.55.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.55.0/path/posix.ts:438:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

Found 4 errors.

**Comment by halvardssm** [comment]
Hi @ThisIsMohsen ! Thanks for submitting this bug! The source of this issue is Deno 1.2 due to the breaking changes with the URL signature. We already have an issue tracking this (#67 ), and we are currently waiting for Denomander and Postgres to create a new release version 👍
