### ISSUE TITLE
[IDEA] foreign key support in table

### ISSUE THREAD

**Issue by uncodable** [halvardssm/deno-nessie#73]
Support to assign a table a foreign key.

**Comment by halvardssm** [comment]
Hi @narwy ! Good idea! I am very busy at the moment, so if you could submit a PR, I can merge it 👍 You can add this method to `Table.ts`

**Comment by halvardssm** [comment]
Will close as query builder is moved to https://github.com/halvardssm/deno-query-builder/issues/1
