### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [halvardssm/deno-nessie#76]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by halvardssm** [comment]
Hi @xcatliu , thanks for submitting this issue! I am a bit unsure how we would use this static site generator with this project, could you explain which website you were thinking about? 😊

**Comment by halvardssm** [comment]
I will close this issue now due to inactivity. Let me know if you have a follow-up, and I can open it up again!
