### ISSUE TITLE
[BUG] std versions prefixed with 'v' were deprecated recently

### ISSUE THREAD

**Issue by mamereu** [halvardssm/deno-nessie#86]
**System (please complete the following information):**
 - Linux 5.9.15-200.fc33.x86_64
 - Deno version 1.6.1
 - Nessie version 1.1.2

**Describe the bug**
Import fails with the following message:
`
Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.61.0/fmt/colors.ts (at https://deno.land/std@v0.61.0/fmt/colors.ts)
error: Import 'https://deno.land/std@v0.61.0/fmt/colors.ts' failed: 404 Not Found
    at https://deno.land/x/denomander@0.6.3/deps.ts:3:0
`

**To Reproduce**
deno cache https://deno.land/x/nessie@v1.1.2/mod.ts

**Comment by aphagon** [comment]
You can use this link cmd => deno cache https://denopkg.com/aphagon/deno-nessie@v1.1.5/mod.ts
