### ISSUE TITLE
[BUG] Expermental Mode never populates nessie_migrations table

### ISSUE THREAD

**Issue by Teddy-Schmitz** [halvardssm/deno-nessie#93]
**System (please complete the following information):**
 - OS: linux
 - Deno version 1.7.2
 - Nessie version 1.1.3

**Describe the bug**
When a migration is run with experimental mode turned on the nessie_migrations table never gets populated.

I took a look at the code in AbstractClient.ts and it seems that if experimental mode is enabled it will never get to QUERY_MIGRATION_INSERT because thats behind the `else` on line 223.

**To Reproduce**
1. Run a migration with experimental mode on
2. Check nessie_migrations table

**Expected behavior**
nessie_migrations table should have values in it.

**Comment by halvardssm** [comment]
Hi @Teddy-Schmitz ! Thank you for submitting this issue! It seems to be the case as you have described, would you like to try to submit a PR? If not, I will have a look over the weekend/next week 😄

**Comment by Teddy-Schmitz** [comment]
Sure I'll take a look at it
